# Generated by Django 2.0.7 on 2019-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('emailid', models.EmailField(default=None, max_length=254)),
                ('address', models.CharField(max_length=400)),
                ('careerobj', models.CharField(default=None, max_length=800)),
                ('qualification', models.CharField(max_length=800)),
                ('education', models.CharField(max_length=800)),
                ('interest', models.CharField(max_length=800)),
                ('references', models.CharField(max_length=800)),
                ('Extraskills', models.CharField(blank=True, max_length=800)),
            ],
            options={
                'db_table': 'detail',
            },
        ),
    ]
